apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: animal-rescue-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: animal-rescue-frontend
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: base-jammy
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-react
    - name: ports
      value:
        - port: 80
          containerPort: 8080
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "start"
  source:
    git:
      # TODO
      #url: <https URL for your generated project's Git repository>
      url: https://github.com/Albertoimpl/animal-rescue-frontend.git
      ref:
        branch: main